# Generated by Django 4.1.5 on 2023-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'Tutor'), (2, 'Student')], default=2),
        ),
    ]
