# Generated by Django 3.2.18 on 2023-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(2, 'Student'), (1, 'Tutor')], default=2),
        ),
    ]
