# Generated by Django 4.1.5 on 2023-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(2, 'Student'), (1, 'Tutor')], default=2),
        ),
    ]
