# Generated by Django 4.1.6 on 2023-03-26 20:14

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_app", "0002_user_tutor_rate_user_tutor_rate_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tutor_rate",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveIntegerField(
                choices=[(2, "Student"), (1, "Tutor"), (3, "Administration")], default=2
            ),
        ),
    ]
