# Generated by Django 4.1.5 on 2023-03-16 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10)),
                ('class_name', models.CharField(default='Some Class', max_length=100)),
                ('available_tutors', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_first_name', models.CharField(default='first', max_length=30)),
                ('tutor_last_name', models.CharField(default='last', max_length=30)),
                ('classlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classlist')),
            ],
        ),
    ]
