# Generated by Django 4.1.5 on 2023-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(default="no class id", max_length=10)),
                (
                    "class_name",
                    models.CharField(default="no class name", max_length=100),
                ),
                (
                    "professors",
                    models.CharField(default="no professor", max_length=100),
                ),
                ("available_tutors", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="classlist",
            name="class_id",
            field=models.CharField(default="cl id", max_length=10),
        ),
        migrations.AlterField(
            model_name="classlist",
            name="class_name",
            field=models.CharField(default="cl name", max_length=100),
        ),
    ]
