# Generated by Django 4.1.7 on 2023-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(default="no class id", max_length=10)),
                (
                    "class_mnen",
                    models.CharField(default="no class mnemonic", max_length=100),
                ),
                (
                    "class_name",
                    models.CharField(default="no class name", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_mnen",
                    models.CharField(default="no class mnemonic", max_length=100),
                ),
                (
                    "professors",
                    models.CharField(default="no professor", max_length=100),
                ),
            ],
        ),
    ]
