# Generated by Django 4.1.7 on 2023-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_classdatabase_alter_classlist_class_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classdatabase",
            name="class_mnen",
            field=models.CharField(default="no class mnemonic", max_length=10),
        ),
    ]
