# Generated by Django 4.1.7 on 2023-04-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="actual_event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_request",
                to="main.event",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="event_id",
            field=models.CharField(default="no event", max_length=255),
        ),
        migrations.AddField(
            model_name="request",
            name="event_start",
            field=models.CharField(default="no event", max_length=255),
        ),
        migrations.AddField(
            model_name="request",
            name="event_stop",
            field=models.CharField(default="no event", max_length=255),
        ),
    ]
