# Generated by Django 4.1.7 on 2023-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_classdatabase_class_mnen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classdatabase",
            name="class_mnen",
            field=models.CharField(default="no class mnemonic", max_length=100),
        ),
    ]
