# Generated by Django 4.0.9 on 2023-02-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_classselect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSelect',
        ),
    ]
