# Generated by Django 4.1.7 on 2023-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_request_actual_event_request_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="day",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="month",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_day",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_month",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
