# Generated by Django 4.1.7 on 2023-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_event_day_event_month_request_event_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_hour",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_hour",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="weekday",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_end_hour",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_start_hour",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_weekday",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
