# Generated by Django 4.0.9 on 2023-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_classes_classlist_rename_availabletutors_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_select', models.CharField(choices=[('CS3240', 'CS3240'), ('ECE2660', 'ECE2660')], default='CS3240', max_length=10)),
            ],
        ),
    ]
