# Generated by Django 4.0.9 on 2023-02-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(choices=[('CS2150', 'CS2150'), ('ECE2660', 'ECE2660'), ('CS3240', 'CS3240'), ('STS4500', 'STS4500')], max_length=10)),
            ],
        ),
    ]
