# Generated by Django 4.0.9 on 2023-02-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='Some Class', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='AvailableTutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=150)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
            ],
        ),
    ]
