# Generated by Django 4.0.9 on 2023-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classes_class_name_alter_classes_class_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletutors',
            name='tutor_name',
        ),
        migrations.AddField(
            model_name='availabletutors',
            name='tutor_first_name',
            field=models.CharField(default='first', max_length=30),
        ),
        migrations.AddField(
            model_name='availabletutors',
            name='tutor_last_name',
            field=models.CharField(default='last', max_length=30),
        ),
        migrations.AddField(
            model_name='classes',
            name='available_tutors',
            field=models.BooleanField(default=False),
        ),
    ]
