# Generated by Django 4.0.9 on 2023-02-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_availabletutors_tutor_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='ClassList',
        ),
        migrations.RenameModel(
            old_name='AvailableTutors',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='classes',
            new_name='classlist',
        ),
    ]
